VERBOSE: False
BASE_TASK_CONFIG_PATH: configs/tasks/rearrange/pick.yaml
TRAINER_NAME: "transformer"
ENV_NAME: "RearrangeRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints"
NUM_ENVIRONMENTS: 4
WRITER_TYPE: 'tb'
# Visual sensors to include
SENSORS: ["HEAD_DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints"
NUM_UPDATES: -1
TOTAL_NUM_STEPS: 2.5e9
LOG_INTERVAL: 10
NUM_CHECKPOINTS: 100
# Force PyTorch to be single threaded as
# this improves performance considerably
FORCE_TORCH_SINGLE_THREADED: True

GYM_AUTO_NAME: "Pick"

RL:


  POLICY:
      name: "TransformerResNetPolicy"
      action_distribution_type: "gaussian"

  REWARD_MEASURE: "rearrangepick_reward"
  SUCCESS_MEASURE: "rearrangepick_success"
  SUCCESS_REWARD: 100.0
  SLACK_REWARD: -0.01
  GYM_OBS_KEYS: ['obj_start_sensor', 'joint', 'is_holding', 'relative_resting_position']

  TRAJECTORY_DATASET:
    trajectory_dir: "data/temp_data"
    steps_per_training: 10000
    trajs_per_file: 5000

  TRANSFORMER:
    lr: 1.0E-4
    eps: 1.0E-5
    grad_norm_clip: 1.0
    use_linear_lr_decay: True
    batch_size: 128
    num_workers: 4




    return_to_go: 128
    
    num_mini_batch: 2
    context_length: 30
    max_episode_step: 200
    model_type: "reward_conditioned"
    n_head: 8
    n_layer: 6
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50

    use_normalized_advantage: False

    hidden_size: 512

    # Use double buffered sampling, typically helps
    # when environment time is similar or large than
    # policy inference time during rollout generation
    use_double_buffered_sampler: False

    sync_frac: 0.6
    # The PyTorch distributed backend to use
    distrib_backend: NCCL
    # Visual encoder backbone
    pretrained_weights: data/temp_data/model.pth # data/ddppo-models/gibson-2plus-resnet50.pth
    # Initialize with pretrained weights
    pretrained: False
    # Initialize just the visual encoder backbone with pretrained weights
    pretrained_encoder: True
    # Whether or not the visual encoder backbone will be trained.
    train_encoder: False

    # Model parameters
    backbone: resnet50